name: Auto Lock Closed Issues

on:
  schedule:
    - cron: "0 */12 * * *"   # Runs every 12 hours
  workflow_dispatch:         

permissions: 
  contents: write 
  pull-requests: write 
  issues: write

jobs:
  lock-closed-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Lock old closed issues
        uses: dessant/lock-threads@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

          issue-inactive-days: 2
          issue-lock-reason: resolved

          process-only: issues
          exclude-any-issue-labels: "pinned,keep-open"

          lock-issue-comment: >
            This issue has been automatically locked because it was closed
            and inactive for 2 days. Please open a new issue if you still
            face the problem.